### ISSUE TITLE
how to append body while updating the draft release

### ISSUE THREAD

**Issue by shreyanshp** [ncipollo/release-action#107]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I am using the following
https://github.com/shreyanshp/gitops/blob/trunk/.github/workflows/cherry_pick_prs.yml#L53

omitBodyDuringUpdate: true
However it does not append, instead just leaves it as it is
https://github.com/shreyanshp/gitops/releases/tag/untagged-93d7dfa9687aa591ebee

**Comment by ncipollo** [comment]
Hi @shreyanshp,

Appending text to the body of the release is out of scope for this action.  This would require a special code path to fetch the existing release, extract the body and then append to it before updating the release. While this is possible it seems like it's probably a pretty specialized use case which is better accomplished via a workflow (rather than within the action itself). Check out this discussion for more context: https://github.com/ncipollo/release-action/discussions/64 .
