### ISSUE TITLE
404 Error on Release

### ISSUE THREAD

**Issue by AllanWang** [ncipollo/release-action#117]
**Describe the bug**

https://github.com/AllanWang/Frost-for-Facebook/runs/3578410019?check_suite_focus=true#step:7:1

Creating a release results in a 404. There aren't any logs as far as I'm aware, but I've populated the necessary fields.

**To Reproduce**
1. Checkout separate project (not the same as the one running the action)
2. Create a commit with a tag
3. Create a release with a body string, the repo + owner values, and with a tag + commit

**Expected behavior**
Release is created

**Additional context**
Main difference is that this upload is for a separate repo. I've created a token with access to the repository, though it's from a different user compared to the repo owner.

**Comment by AllanWang** [comment]
Perhaps for debug logs, could this action output the expected tag url to confirm that the repo is correct?

I've confirmed that the previous steps do commit, tag, and upload to the proper repo:

https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2944

**Comment by AllanWang** [comment]
Solutions:

Repo turns out to be just the repo name (https://github.com/ncipollo/release-action/blob/a4548f83be1cd50c4880498fe95a42ede0368dc5/lib/Releases.js#L43). In action/checkout, repository = slug (owner + repo), so I used the wrong one. Having the url print in debug would be helpful

Specifying a commit hash while the tag is already created will result in `Error: Error 422: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}
`. Just an fyi for those who see this, though it may be nice to mention in the readme

**Comment by ncipollo** [comment]
Hi @AllanWang,

A few notes based on comments in the issue:

> In action/checkout, repository = slug (owner + repo), so I used the wrong one. Having the url print in debug would be helpful

I'm using the octokit library within the action which obfuscates the underlying URL a bit, so I don't think it makes sense to print out the URL for debugging. You can, however, see the inputs you provide into the action by expanding the `Run ncipollo/release-action@v1` line in the logs.

> Specifying a commit hash while the tag is already created will result in Error: Error 422: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"} . Just an fyi for those who see this, though it may be nice to mention in the readme

I would actually be surprised if the API was failing due to tag already existing. The documentation indicates that this field will be ignored if the release exists (for both create and update calls). You might want to double check that the commit hash you were providing was actually valid. See https://docs.github.com/en/rest/reference/repos#create-a-release

It sounds like you've resolved the issue by fixing the `repo` input, I'm going to close out since I don't think there's any additional action to take here.

**Comment by AllanWang** [comment]
I can see my inputs, though my issue was that I made the repo string the slug. Admittedly, it's weird to have that while an owner field exists, though I was coming from action/checkout and assumed that repo = repository.full_name. My only suggestion would be to add an example in the documentation (ie `(eg release-action)`), or to print a github url yourself.

---

https://github.com/AllanWang/Frost-for-Facebook/runs/3578449818?check_suite_focus=true#step:7:9

this is an example with the commit hash. The commit is indeed a shorter hash, but that was the output of a separate action. I can verify it does work as https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/commit/b52299c resolves, so I guess octokit requires a complete hash?

**Comment by ncipollo** [comment]
Cool, yeah I'll add an example.

> so I guess octokit requires a complete hash

Yeah, I'm not really sure. Unfortunately the documentation doesn't provide a ton of detail on this other than that it could be a commit hash or a branch :( .
