### ISSUE TITLE
Failed to upload some artifacts

### ISSUE THREAD

**Issue by OpportunityLiu** [ncipollo/release-action#12]
Artifacts randomly failed to upload these days. Should an option of retry be added?

![图片](https://user-images.githubusercontent.com/13471233/75602962-1136f580-5b05-11ea-9487-3ee721ac9e08.png)
![图片](https://user-images.githubusercontent.com/13471233/75602968-172cd680-5b05-11ea-99fc-af889e68ecc3.png)

**Comment by ncipollo** [comment]
Hmm, I'm not sure how a retry would work, but I could look into allowing the action to replace existing artifacts if they already exist.

**Comment by ncipollo** [comment]
I updated the action so it will replace existing artifacts if you run it again (with allowUpdates set to true). Not sure this will 100% fix your problem since I'm not sure why github randomly fails for some of the artifacts... but you can at least re-run your workflow now 🙃 .

Feel free to re-open or create a new issue if this continue to cause issues. I could have it retry once or twice if it fails but I suspect that if there are intermittent issues with the github api it would still fail.

**Comment by OpportunityLiu** [comment]
If run the action twice is regarded as a solotion, the original version (skip existing artifacts) DO solve the problem, except that you got a warning for every artifact succeeded in the first upload.

If you replace existing artifacts, the first run is meaningless since you delete and re-upload them at the second run.

**Comment by OpportunityLiu** [comment]
I've added some debug output and found this:

![图片](https://user-images.githubusercontent.com/13471233/75853353-dbf21680-5e28-11ea-8954-271069812a66.png)
I think it's ok to retry when we got a 5xx response

**Comment by ncipollo** [comment]
Thanks for the fix @OpportunityLiu !
