### ISSUE TITLE
Published releases are overriden

### ISSUE THREAD

**Issue by ilopmar** [ncipollo/release-action#21]
We use this action with the flag `allowUpdates` set to `true` because we want to update "Draft" PRs with the latest changes until we manually do a release.
Today it, because of a miss configuration on our side, this action as reverted from published to draft a release we had. This happened because of the `allowUpdates' flag, but I think this is a bug, because a published version should never be updated (even with that flag).

**Comment by ncipollo** [comment]
Hi @ilopmar,

Unfortunately this is an intentional design decision. I want to avoid making too many assumptions in the action since that reduces the overall flexibility within workflows. If both `allowUpdates` and `draft` are set to `true`, the action will assume your workflow allows for moving releases back to draft after being published.

Additionally, I would argue that this specific configuration can be desirable in some cases. For example:
- If your project maintains a `v1` or `latest` release. You can setup your workflow to update this release when you update these tags.
- If your organization needs to pull back a release (for example, they found a critical bug last minute).

In your specific case, I believe you can resolve this with workflow conditionals. Checkout https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions
For example:
- Utilize an action to fetch a github release (ex- https://github.com/marketplace/actions/get-latest-release)
- Add a conditional to the release-action step which skips the step if the release already exists.

**Comment by ilopmar** [comment]
Thanks for the feedback. We've done something like you've proposed.
