### ISSUE TITLE
Slash not supported in release tag name

### ISSUE THREAD

**Issue by igorpecovnik** [ncipollo/release-action#224]
When using tag this way:

tag: "a/b" it fails with:

Error 500: invalid json response body at https://api.github.com/repos/armbian/mirror/releases reason: Unexpected end of JSON input

While it works well if tag does not contain / 

I was using https://github.com/svenstaro/upload-release-action before and there / is accepted, Github supports it.

**Comment by ncipollo** [comment]
The action & github do seem to support slashes in the tag name, but as @fiddlermikey alluded to, git actually treats slashes in ref names as hierarchical (created a folder on the filesystem). So if you are receiving and error it might be because tag `a` already exists. 

Here's an example of the action working correctly with `a/b` (note I don't have a `a` tag) -https://github.com/ncipollo/actions-playground/actions/runs/3169749767/jobs/5161873130

**Comment by mk-pmb** [comment]
Thanks! I just hit the same error with a prefix tag existing from earlier work. Can we maybe get a better error message in those cases? I assume there may already be a useful error message be received instead of the JSON, so can we just preview like the first 1024 bytes of the non-JSON response?
