### ISSUE TITLE
Release Validation Failed

### ISSUE THREAD

**Issue by kslr** [ncipollo/release-action#3]
Hi 

What is the cause of this error, I used an automatic TAG, is it possible that the problem?
> https://github.com/EndBug/latest-tag

> https://github.com/v2fly/geoip/commit/ab78bfd2bbbd85857140311f74157cd784a40853/checks?check_suite_id=282919650

> https://github.com/v2fly/geoip/blob/master/.github/workflows/main.yml

**Comment by ncipollo** [comment]
Hi,
I think that error is coming from octokit (the library I use to generate releases). It's unfortunately kind of generic but I suspect octokit is failing to create a release because one already exists with the desired name.  The action is currently intended to create a release and doesn't have any logic for updating an existing release.

**Comment by kslr** [comment]
Ok, I will check this question further later.

**Comment by kslr** [comment]
I solved it by updating the resource file.
