### ISSUE TITLE
Fails to Replace Existing Artifacts with Same Name

### ISSUE THREAD

**Issue by howyay** [ncipollo/release-action#33]
**Describe the bug**
release-action fails when trying to upload artifacts to replace existing artifacts in an existing release.

**To Reproduce**
1. Create a release through conventional methods or this Github Action with artifact `example.zip`
2. Set both `allowUpdates` and `replacesArtifacts` to `true` when creating a release with same name and tag
3. In the same workflow job and step as the (reproduction) step above, upload an updated version of `example.zip`
4. Upload fails but the workflow job continues

**Expected behavior**
When `allowUpdates` and `replacesArtifacts` are set to true, this Github Action should delete and replace the existing artifact with the new version of the artifact of the same name, as provided in the `artifact` or `artifacts` input.

Also, when the upload fails, the workflow should probably fail too, to indicate that something has gone wrong.

**Screenshots**
`macos-latest` error msg 1
![图片](https://user-images.githubusercontent.com/28365438/111891811-98dff280-89ed-11eb-8d8c-3099e7f0bffd.png)
`macos-latest` error msg 2 (it somehow printed the HTML code from Github...?)
![图片](https://user-images.githubusercontent.com/28365438/111891851-f2482180-89ed-11eb-9053-8b1c92838236.png)
`ubuntu-latest` error msg
![图片](https://user-images.githubusercontent.com/28365438/111891819-a8f7d200-89ed-11eb-8f68-5aee0efe8fba.png)
`windows-latest` error msg 1
![图片](https://user-images.githubusercontent.com/28365438/111891830-bc0aa200-89ed-11eb-9540-db674c8d446a.png)
`windows-latest` error msg 2
![图片](https://user-images.githubusercontent.com/28365438/111891882-3804ea00-89ee-11eb-9a37-1cbae4b36323.png)

**Github Action Virtual Environment:**
 - OS: `macos-latest`, `ubuntu-latest`, and `windows-latest`

**Additional context**
The error message is different for each different OS used for Github Action virtual environment.

**Comment by ncipollo** [comment]
Hi @howyay,
Thanks for the detailed bug report! I took a look and I suspect this is failing for you because you are running a matrixed set of jobs (assuming this is the correct workflow file: https://github.com/howyay/ytmdesktop/blob/development/.github/workflows/nightly.yml#L15). By default I believe github will run these in parallel... which is going to lead to a somewhat unpredictable interaction with the release action. I think what we are seeing is multiple jobs are attempting to save artifacts to the release at the same time and we are running into naming collisions. So even though the action is deleting the old assets in `Job A`, it doesn't see the assets saved by `Job B` in time and we end up with a naming collision.

I'll look to see if it makes sense to try and improve the error handling logic in the artifact uploading code, but I'm not sure it's going to be possible to completely handle parallel interaction with the release in a predictable way.

> Also, when the upload fails, the workflow should probably fail too, to indicate that something has gone wrong.
Good idea, I'll add an option to fail on collision.

**Comment by ncipollo** [comment]
Hmm, so I looked into it a bit and I don't think I can protect against this case when you are running parallel builds. I was hoping the github API had some kind of mechanism to atomically replace an artifact, but that doesn't seem to be the case. The only documented mechanism I can find is https://docs.github.com/en/rest/reference/repos#upload-a-release-asset. Since there is no atomic update, there is no way to protect against a parallel job adding the asset in between when the initial job deletes it and when it tries to upload the new one.

**Comment by ncipollo** [comment]
Added a flag so you can fail the build if an artifact fails to be read or uploaded, see details here: https://github.com/ncipollo/release-action/releases/tag/v1.8.2

Unfortunately I don't think there's really much we can do about parallel jobs running and getting artifact conflicts. I'd either try forcing your jobs to run synchronously or ensure that each artifact has a unique name (maybe append the current platform as a prefix or suffix to each)

**Comment by howyay** [comment]
Hi! Thank you for your time and your thorough investigation! 

The files are actually named uniquely with a tag for their respective platform in the file name, and I attempted running the job with 1 max-parallel, but it seemed to have failed to the same error. 

I'm not sure what the real issue is here, does Github just not allow overriding files in reality?
I understand that this issue may be stale due to API limitations on Github's end, but I will keep investigating this issue myself.

**Comment by ncipollo** [comment]
> Hi! Thank you for your time and your thorough investigation!
No problem! I'm sorry my investigation didn't seem to address the issue you are seeing 🙃 .

> The files are actually named uniquely with a tag for their respective platform in the file name, and I attempted running the job with 1 max-parallel, but it seemed to have failed to the same error.

Hmm, that is surprising. It might be helpful to enable debug logging, we print out some debug logs before asset upload and when we delete an existing asset. See https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging

 > I'm not sure what the real issue is here, does Github just not allow overriding files in reality?
So as far as I know there isn't a mechanism to do this purely via the github API. When you set `replacesArtifacts` to `true` we do the following:
- Pull all existing assets from the release
- Match existing assets with new ones we are trying to upload (by name)
- Delete each match we find
- Upload new assets

As far as I can tell this process typically functions correctly, at least I haven't seen any issues in any of the repos where I am using this action. I have a test repo setup here which replaces the artifacts - https://github.com/ncipollo/actions-playground/blob/master/.github/workflows/tag.yml

The documentation for the upload asset endpoint does mention that they will rename assets which have special characters in the name: https://docs.github.com/en/rest/reference/repos#upload-a-release-asset
This could potentially mess with the above flow since I don't think we would be able to correctly match the new asset to the old one when trying to replace. You might want to try sanitizing the asset names (remove special characters) to see if that helps. See https://docs.github.com/en/rest/reference/repos#upload-a-release-asset

> GitHub renames asset filenames that have special characters, non-alphanumeric characters, and leading or trailing periods. The "List assets for a release" endpoint lists the renamed filenames. For more information and help, contact GitHub Support.

**Comment by ncipollo** [comment]
Hmm, yeah maybe I should add some handling for when the upload fails with an already existing asset error. Not sure that would help in the case where parallel jobs are running but if you are hitting this issue because github is renaming your assets it would help.

**Comment by ncipollo** [comment]
Took a look and unfortunately there doesn't seem to be a way to replace an asset if the github changed the name after you uploaded it. I was hoping the `already_exists` error would provide me with the asset ID but it doesn't seem to, so I have no way of matching the new asset against the old :(

If this is indeed the problem you are hitting I'd recommend trying to rename the files so they don't contain special characters.

**Comment by Koushikphy** [comment]
I was publishing a nodejs app executable with this action and had this problem. It seems my application was being generated with a name that has space in it and github converted them to ".". When I explicitly set the name removing the spaces, this action works properly.
