### ISSUE TITLE
Changing node version should bum major version

### ISSUE THREAD

**Issue by RobertDeRose** [ncipollo/release-action#416]
**Describe the bug**
1.14.0 bumped the node version from 16 to 20.  This is a major change. It would have been nice if the version bumped to v2 for this changed.

Reason: Custom runners might not have the latest node version yet and this will break otherwise working workflow.

This happened to us :(

**Comment by ncipollo** [comment]
I'll drop a post in discussions to make raise the visibility level of this change but unfortunately I don't agree that it constitutes a major version bump. A couple of reasons:
1. While this can be a breaking change for some configurations, it is not a change to the API of the action & therefor not an API breaking change (see https://semver.org/). If it weren't for the next point I could maybe be swayed the change in node version constitutes an API change, though we'd probably need to debate that point a little bit 🙃.
2. More importantly Github will be enforcing all actions run on node20 in spring since node16 is end of life. Even if I did nothing in the action you would mostly likely run into this same issue in a couple of months when they pull the trigger. See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

All that said, I apologize for the lack of visibility here. I should have sent out an announcement along with this change.

**Comment by RobertDeRose** [comment]
OK, fair enough.

I was just thinking that since Github up all their actions with a new major, they must consider it a breaking change as well. 

For now I have just locked myself to 1.130.0 until I can get the person that maintains our self-hosted runners to upgrade them
