### ISSUE TITLE
TOCTOU when two jobs try to create a release at the same time

### ISSUE THREAD

**Issue by marysaka** [ncipollo/release-action#420]
**Describe the bug**

I just caught this on our CI (https://github.com/Ryujinx/Ryujinx/actions/runs/7857604048/job/21441682303), for some reasons instead of trying to update the already existing release, it errored out.

**To Reproduce**

Try to run two jobs that finish at the time I guess? not sure how reproducible this is...

**Expected behavior**

The action just retry but this time update the already existing release.

**Comment by ncipollo** [comment]
This is out of scope for this action. If you want to add a retry you can provably do that in the workflow itself. That being said, I would recommend against trying to manage releases from multiple parallel jobs. You are going to run into lots of race conditions like this since you are effectively mutating shared state from multiple, async jobs.

**Comment by marysaka** [comment]
> This is out of scope for this action. If you want to add a retry you can probably do that in the workflow itself. That being said, I would recommend against trying to manage releases from multiple parallel jobs. You are going to run into lots of race conditions like this since you are effectively mutating shared state from multiple, async jobs.

Well it has never happen here until that point (so a solid 2 years at least)

I suppose I will enforce creation of the release early on when we create the tag on the main repo then.
