### ISSUE TITLE
New feature: being able to extract and inject part of existing changelog files to the release body

### ISSUE THREAD

**Issue by stronk7** [ncipollo/release-action#421]
**Is your feature request related to a problem? Please describe.**
Not a big problem, other actions provide that, but I think it may have sense to implement it straight into this action, hence, sharing.

Similarly to the current feature that allows the action to fill the release notes from GH release API automatically, it would be great if the actions was able to extract the release notes from a manually/custom/other sytem maintained `CHANGELOG.md` file.

**Describe the solution you'd like**
Basically, if a path to a changelog file is specified, and if the changelog file is [correctly structured](https://keepachangelog.com/), then the information will be extracted from that file (for the version being released) and injected into the "body", surely at the very beginning by default but, if some `{{PUT_CHANGELOG_HERE}}` (template-like) is detected in the body, then the information should go there.

**Describe alternatives you've considered**
As said, I'm using other actions or custom scripts to perform the extraction from different changelogs or other systems and then, adding them to your action adding outputs from other steps to the body.

Just thought that, maybe, the use case (having a wellformed changelog file in the repo) is frequent enough to consider supporting it from within the action.

**Additional context**
Ciao :-)

**Comment by ncipollo** [comment]
Thanks for the suggestion! However, I want to keep the scope of this action focused around the management of the release itself. As you mention there are other actions which can be used to generate the body from a change log file, etc. I think keeping this functionality separate from the release generation offers the greatest flexibility since you can compose chose from a variety of approaches within the workflow itself.
