### ISSUE TITLE
[error] Validation Failed

### ISSUE THREAD

**Issue by hyll8882019** [ncipollo/release-action#5]
I can't speak English. I try to use translation to describe my problems
When I build multiple versions and release them, the following error occurs
```
Run ncipollo/release-action@v1
##[error]Validation Failed
##[error]Node run failed with exit code 1
```
It seems that only one submission can be made
[This is my test address](https://github.com/hyll8882019/HelloAction/commit/bc96ce38d9c55108cbf324a63a348db1a6500ae7/checks?check_suite_id=344729075)

**Comment by ncipollo** [comment]
Hey!

This action will only create a release, it will not update an existing release. Even if it did I suspect you would have issues because you are running 3 separate workflows for the 1 tag. It would be somewhat random which one finishes first. Could you generate all 3 artifacts in a single workflow? If so you can use the artifacts input to specify all 3.

**Comment by hyll8882019** [comment]
谢谢.  我希望能支持更新发布. 因为我实际项目中,不能做到同时生成3个版本.

**Comment by ncipollo** [comment]
@hyll8882019,
A couple of updates:
- The action can now support updating a release. Set the `allowUpdates` input to `true` to set this up.
- Error output should now provide more robust error information. For example, if would let you know if the update already existed (if allowUpdates is off).
