### ISSUE TITLE
Unable to get draft update working

### ISSUE THREAD

**Issue by sondreb** [ncipollo/release-action#8]
I'm trying to use the action to create a new release and update that release. Unfortunately it keeps creating new releases.

Have done what is mentioned in the notes, specifying both tag and commit, but still creates duplicates. Have tried with bot the sha variable, and "master".

It appears perhaps that the tag is not created?

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{env.RELEASE_NAME}}"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        prerelease: true
        name: "City Chain (Release ${{env.VERSION}})"
        #commit: "${{github.sha}}"
        commit: master
        tag: v${{env.VERSION}}

Screenshot of produced releases:

![image](https://user-images.githubusercontent.com/309938/71449863-28e5ac80-2757-11ea-8d12-76dcf302f3d5.png)

**Comment by ncipollo** [comment]
Hi!

The issue is that GitHub allows you to have multiple drafts which point to the same tag (unlike normal releases). I'm not sure of the best way to updating draft releases because of this (should the action update all, just the most recent, etc).

**Comment by giancarlokc** [comment]
I've run into the same issue. I have a build for each platform (Linux, Windows and Mac) and a need to push all artifacts into the same draft release.

I know I can do that by using two separate actions (one to create release and another to update the artifacts), but your action was interesting because of this update feature. Hopefully there's a way to force udpates to draft releases.

**Comment by ncipollo** [comment]
The action will now attempt to update draft releases. A few notes:
- The action will still prefer to update a published release if one exists for a given tag (i.e it would update this rather than a draft pointing to the same tag).
- If multiple drafts exist which point to the same tag it will only update the first one it encounters.
- If the draft release is super old, such that it's not within the first page of release results, it will not get updated. This is an intentional tradeoff to avoid needing to send multiple `releases` requests to github.

**Comment by simontom** [comment]
Hi, is it possible to update already existing file in Draft-Release?

**Comment by ncipollo** [comment]
@simontom,
It's not currently possible to overwrite an existing artifact, I'll take a look at adding an option for that.

**Comment by mrchief** [comment]
When it updates the draft release, can it also update the status? E.g., 

```
          allowUpdates: true
          draft: false
          ...
```

also updates the draft release to published?

**Comment by ncipollo** [comment]
@mrchief ,
As far as I can tell this scenario should work. If you look at the following two action runs, I start with a draft, then update it to be a published release:
- https://github.com/ncipollo/actions-playground/actions/runs/184717019/workflow
- https://github.com/ncipollo/actions-playground/actions/runs/184718632/workflow

Apologies if I'm misunderstanding your use case.

**Comment by mrchief** [comment]
Yeah it's similar to what I tried but for me it created a draft release.
